### ISSUE TITLE
Lack of milestones and tags for bugs relevancy/importance/difficultiness

### ISSUE THREAD

**Issue by vishnumani2009** [ClimbsRocks/auto_ml#125]
Hi Preston,
- Currently I am able to see many issues opened, but not being assigned to/part of any milestones.
- Do you have any  plans for upcoming release? 
- Also I feel there is a need of tags assigned to each issue to make sure newbies get started easily and existing contributors to select issues to work on.
- As projects becomes mature this could benefit both contributors and code reviewers a lot.
- what you opinion on this?

best,
Mani

**Comment by ClimbsRocks** [comment]
Yep, great idea. Makes sense. I'll go through and organize the project a bit more this weekend. Thanks for raising this issue!

**Comment by vishnumani2009** [comment]
I can help you with this. Let me know if you want any support
