### ISSUE TITLE
UnboundLocalError: local variable 'prediction_data' referenced before assignment

### ISSUE THREAD

**Issue by akodate** [ClimbsRocks/auto_ml#129]
And here's the predict_proba issue I mentioned.

```
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-9-68594bcd70e0> in <module>()
----> 1 ml_predictor.predict_proba(tournament_df)

/Users/alex/Desktop/Machine Learning/auto_ml/auto_ml/predictor.pyc in predict_proba(***failed resolving arguments***)
    836 
    837         del prediction_data
--> 838         return self.trained_pipeline.predict_proba(prediction_data)
    839 
    840 
```

**Comment by ClimbsRocks** [comment]
thanks for finding this! we only get predictions from these pipelines after saving them, so we didn't run into this bug. should be fixed both on master and on PyPi as of the release that just got pushed out. 

that release should take care of that other bug you note too. the several import statements are certainly messy, but let me use it as either an installed package, or the entire repo downloaded from github, in python 2.7 and 3.x. but i'm super open to a PR if you want to clean that up a bit.

let me know if you run into any other bugs!
