### ISSUE TITLE
TypeError: cannot perform reduce with flexible type OR AttributeError: 'Predictor' object has no attribute 'grid_search_pipelines'

### ISSUE THREAD

**Issue by calz1** [ClimbsRocks/auto_ml#163]
Very cool package!

I am trying out auto_ml with [this dataset](https://archive.ics.uci.edu/ml/datasets/SMS+Spam+Collection) on SMS spam. I added a header row to the file to give it column names and then do the following:

```
import pandas as p  
import dill  
from sklearn.model_selection import train_test_split   
from auto_ml import Predictor 

df = p.read_table('/home/data/auto_ml/sms.txt')
df_train, df_test = train_test_split(df, test_size=0.5, random_state=42)
column_descriptions = {
  'spam': 'output'
  , 'text': 'nlp'
}

ml_predictor = Predictor(type_of_estimator='classifier', column_descriptions=column_descriptions)
ml_predictor.train(df_train)
```

You can see it sort of works because it is telling me about feature importance but then gives :

> ....
> nlp_text_txt: 0.0373
> nlp_text_free: 0.0441
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python2.7/dist-packages/auto_ml/predictor.py", line 597, in train
>     if len(self.grid_search_pipelines) > 1:
> AttributeError: 'Predictor' object has no attribute 'grid_search_pipelines'
> 

Originally I was trying: 
`ml_predictor.train(df_train,ml_for_analytics=True)`

and got: 

>  test_score = ml_predictor.score(df_test, df_test.spam)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python2.7/dist-packages/auto_ml/predictor.py", line 1014, in score
>     score, probas = self._scorer.score(self.trained_pipeline, X_test, y_test, advanced_scoring=advanced_scoring)
>   File "/usr/local/lib/python2.7/dist-packages/auto_ml/utils_scoring.py", line 268, in score
>     score = self.scoring_func(y, predictions)
>   File "/usr/local/lib/python2.7/dist-packages/sklearn/metrics/classification.py", line 1884, in brier_score_loss
>     pos_label = y_true.max()
>   File "/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py", line 26, in _amax
>     return umr_maximum(a, axis, None, out, keepdims)
> TypeError: cannot perform reduce with flexible type

**Comment by ClimbsRocks** [comment]
Sweet, I'll look into this tomorrow! Any chance you can share the dataset?

**Comment by calz1** [comment]
Here's a [direct link](https://archive.ics.uci.edu/ml/machine-learning-databases/00228/smsspamcollection.zip). All I added was a row on top like so:

> spam (tab) text

**Comment by ClimbsRocks** [comment]
Thanks for sending the link (again)! I had f.lux removing all the blue light when I looked at this last night so I missed the link the first time 😛 

I found the issue. For binary classification problems, we currently assume that the output is `{0, 1}`. 

Sometime this weekend I'll go through and make auto_ml more flexible to handle strings as our labels. 

In the meantime, just replace "spam" with 1 and "ham" with 0 and you should be set! Here's the code that ended up working for me:

```
import pandas as pd
import dill
from sklearn.model_selection import train_test_split
from auto_ml import Predictor

df = pd.read_table('sms2.txt')
df.columns = ['spam', 'text']

def spam_formatter(val):
    if val == 'spam':
        return 1
    elif val == 'ham':
        return 0

df['spam'] = df.spam.apply(spam_formatter)

df_train, df_test = train_test_split(df, test_size=0.5, random_state=42)
column_descriptions = {
  'spam': 'output'
  , 'text': 'nlp'
}

ml_predictor = Predictor(type_of_estimator='classifier', column_descriptions=column_descriptions)
ml_predictor.train(df_train)

print('Saving trained predictor to file so we can use it elsewhere')
ml_predictor.save()

print('Score on test data:')
ml_predictor.score(df_test, df_test.spam)

print('Score on training data to ensure we are not overfitting:')
ml_predictor.score(df_train, df_train.spam)
```

Thanks for filing this! It's an improvement I've had in the back of my mind for a while, but never had to prioritize since none of my datasets were structured this way. 

Let me know if you run into anything else that's unclear or could be improved! 

P.S. It looks like XGBoost is more accurate for this particular split than scikit-learn's GradientBoostingClassifier. It can be a pain to install, but is an easy accuracy boost when you want it :)

**Comment by calz1** [comment]
Thanks for the quick response. Using your function to relabel as 0 and 1 worked. That wouldn't be a huge deal if it was documented, though if usability is your goal it would be a nice feature. Installing XGBoost via pip wasn't bad at all and definitely improved the accuracy.

What's the chance of having multivariate classification supported?

**Comment by ClimbsRocks** [comment]
Oh sweet, thanks for letting me know the pip install for xgboost works now! We broke quite a few engineers' computers at work when that behaved unexpectedly in the past...

Multivariate classification should work. Under the hood, we detect whether it's a binary or multiclass classification problem, so I don't think there's anything you need to do to note that difference. 

I think we might only support `accuracy` score for now, but it's been a while since I've done a multivariate problem, so I'm a bit hazy on that part of the codebase. Put it to use and let me know what you think! I'll try to note that in the docs too.

**Comment by ClimbsRocks** [comment]
Yeah, good call, I just updated the docs to note that labels have to be integers. It actually adds a fair bit of complexity to do that automatically (and forces me to make some UX decisions I haven't spent any time thinking through yet).

 Let me know what else ya run into as you use this @calz1 ! I know it works really well for all the common use cases of about a dozen us at work, but there's quite a bit in between that I haven't used it for extensively yet.

**Comment by calz1** [comment]
I am trying out regression and unfortunately got a similar sounding error:

> DestAirportID: 0.1734
> DepDelay: 0.3498
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/lib/python3.4/site-packages/auto_ml/predictor.py", line 597, in train
>     if len(self.grid_search_pipelines) > 1:
> AttributeError: 'Predictor' object has no attribute 'grid_search_pipelines'

This time I'm using the data set described [here](https://gallery.cortanaintelligence.com/Experiment/Binary-Classification-Flight-delay-prediction-3#azureml-experience-anchordisplayanchor-1) saved as CSV. I can send a copy, but it is 23MB compressed.

My full code was:

```
import pandas as p  
import dill  
from sklearn.model_selection import train_test_split   
from auto_ml import Predictor 

df = p.read_table('air.csv', sep=",")
df_train, df_test = train_test_split(df, test_size=0.5, random_state=42)
column_descriptions = {
  'Year': 'categorical'
  , 'Month': 'categorical'
  , 'DayofMonth': 'categorical'
  , 'DayOfWeek': 'categorical'
  , 'Carrier': 'categorical'
  , 'OriginAirportID': 'categorical'
  , 'ArrDelay': 'output'
}


ml_predictor = Predictor(type_of_estimator='regression', column_descriptions=column_descriptions)
ml_predictor.train(df_train)
```

**Comment by ClimbsRocks** [comment]
@calz1 : 

1. Darn- sorry you're finding some burrs I wasn't aware of. 
2. Thanks for filing issues!
3. What version of auto_ml are you using? The latest is 1.10.0 (just released yesterday, I believe). If you're not using that version, a simple `pip install --upgrade auto_ml` should do  the trick. 

I'll look more into this now.

**Comment by ClimbsRocks** [comment]
huh, yeah, that's really weird. looking through the `Predictor` code, we set `self.grid_search_pipelines = []` right inside `__init__`. And then the only thing we do to it is try to append. After training, we delete it, but you're not even getting that far. 

It looks like our row numbers are a bit off. I'm hoping this was some bug in a previous version I missed that is fixed now. But I'd love to know which version you're on (`pip freeze`) so I can look into this a bit more. 

Thanks again for filing this issue!

**Comment by calz1** [comment]
No need to apologize, the idea is a cool one and you're doing the community a great service by looking into issues so quick.

I was using:

> auto-ml==1.9.7
> xgboost==0.6a2

and upgrading auto_ml fixed it! I will continue experimenting...

**Comment by ClimbsRocks** [comment]
yay!
