### ISSUE TITLE
xgboost in advanced_requirements.txt unreliable

### ISSUE THREAD

**Issue by calz1** [ClimbsRocks/auto_ml#187]
I am partially to blame because I think I pointed out that xgboost was now in pip but there's some bad news: it appears the version in pip still suffers from a bug that some guy named @ClimbsRocks ran into last summer. 

https://github.com/dmlc/xgboost/issues/1238

In other words, I ran into that same ragged data problem when attempting to predict. After reading the thread, I was able to fix it  relatively easily by installing XGBoost like described [here](https://xgboost.readthedocs.io/en/latest/build.html#building-on-ubuntu-debian) but you may want to consider backing out the auto install to avoid other people logging XGBoost issues...

**Edit:** I realized I oversimplified the install to fix this. For Ubuntu, it was the link I said and then the steps farther down that page to install the python package. Together, it is:

`git clone --recursive https://github.com/dmlc/xgboost
cd xgboost; make -j4`

`cd python-package; sudo python setup.py install
`

**Comment by ClimbsRocks** [comment]
Drats- I'd forgotten how old that distribution was. I just recently cleaned that workaround out of the codebase as part of some simplification work. Good call on removing XGBoost from the `advanced_requirements.txt` file for now. Thanks for the continued input!

**Comment by calz1** [comment]
I see this is gone in the latest version so I think it is moot.
