### ISSUE TITLE
progress bar for feature transformation pipeline

### ISSUE THREAD

**Issue by ClimbsRocks** [ClimbsRocks/auto_ml#242]
give people a sense of what's taking a long time

have self.is_first_transform = True for all our wrappers
Then have both "Fitting X pipeline component" and "Transforming with X pipeline component", but making sure we only do this the first time

**Comment by SasankYadati** [comment]
I would like to take this up.

**Comment by ClimbsRocks** [comment]
thanks for reaching out @SasankYadati ! sorry i just noticed this. i actually finished this up in a recent release. 

what i was shooting for was just to give users a sense of progress, so they could understand the different steps we were going through, and have some markers along the way to tell them how close to training time they were if they got antsy. 

if you want to help on some other issues though, let me know! i think there's still a lot we can do around printing scoring metrics, and automated data exploration. those modules are relatively self-contained, so they're pretty easy to work on. they're also used each and every time someone uses auto_ml, so it would be pretty big impact.

**Comment by SasankYadati** [comment]
@ClimbsRocks Thanks for replying. I am definitely interested in taking up other issues. BTW, I am new to open source contribution and I would appreciate your guidance in regards to this.

I wonder if there are any issues that are beginner friendly that I would be able to work with.
