### ISSUE TITLE
write tests

### ISSUE THREAD

**Issue by ClimbsRocks** [ClimbsRocks/auto_ml#26]

**Comment by ClimbsRocks** [comment]
Duplicate for both regressors and classifiers
numerai for classifiers, and rossmann for regressors?
- [ ] should get a score below X on the given dataset
- [ ] should take in a list of dictionaries, or a dataframe
- [ ] should remove columns marked ignore
- [ ] should have a certain size after BasicDataCleaning
- [ ] should have all values between 0 and 1 after CustomSparseScaler
- [ ] should be a matrix after DataFrameVectorizer
- [ ] should not have any nan or inf values after DataFrameVectorizer
- [ ] should have a certain size after feature selection
- [ ] should return a 1-d list of scalar values from predict and predict_proba
- [ ] should return a single value if a single item was passed in
- [ ] should take in a single item for predict and predict proba
- [ ] should be faster than X seconds for 1000 calls to predict with a single object
- [ ] should print ml_for_analytics results
- [ ] should train up subpredictors (might have to test this with weak estimators)
- [ ] should train up weak estimators if told to
- [ ] should train in less than X seconds for a given dataset 
- [ ] ideally, should have a certain memory footprint
- [ ] some tests around grid search and hyperparameter optimization. not sure how yet. 
- [ ] test different model names to make sure it'll actually train up all the models we want it to. 
- [ ] test all of our user logging
- [ ] a column with all nan values should be removed
- [ ] a column with all the same value should be removed
- [ ] a column with a mix of 1's and nans should stay as is

obviously this is all very hardware dependent, which is difficult. could definitely work around that by integrating with circleci, and running on their hardware, which will be consistent. 

we also don't want to include the raw data when a user downloads and installs the repo by itself. so maybe the first step is to download it from a publicly available api (like my dropbox account or something?)

**Comment by vishnumani2009** [comment]
Hi preston,
I am working this 
I will send the PR's incrementally.

**Comment by ClimbsRocks** [comment]
Hi Mani,

That's awesome! We'll probably have some overlapping work here, since this is something I'll be working on pretty actively over the next few days, but I'd love your help on it. The refactor to using DataFrames was unnecessarily difficult because we didn't have a good test suite built out to verify that things were working as expected. 

Building out a good test suite should be really helpful for contributors, because they can make changes and not worry about breaking things accidentally. 

Can't wait to have that available!

Warmly,
preston

**Comment by ClimbsRocks** [comment]
tested, and with CI!
