### ISSUE TITLE
ValueError: Iteration of zero-sized operands is not enabled

### ISSUE THREAD

**Issue by azuric** [ClimbsRocks/auto_ml#314]
Hi

I am getting this error

> 
> About to fit the pipeline for the model GradientBoostingRegressor to predict s3diff
> Started at:
> 2017-08-16 08:46:46
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Anaconda3\lib\site-packages\auto_ml\predictor.py", line 566, in train
>     self.trained_final_model = self.train_ml_estimator(estimator_names, self._scorer, X_df, y)
>   File "C:\Anaconda3\lib\site-packages\auto_ml\predictor.py", line 993, in train_ml_estimator
>     trained_final_model = self.fit_single_pipeline(X_df, y, estimator_names[0], feature_learning=feature_learning, prediction_interval=False)
>   File "C:\Anaconda3\lib\site-packages\auto_ml\predictor.py", line 762, in fit_single_pipeline
>     ppl.fit(X_df, y)
>   File "C:\Anaconda3\lib\site-packages\auto_ml\utils_model_training.py", line 129, in fit
>     best_model = deepcopy(self.model)
>   File "C:\Anaconda3\lib\copy.py", line 182, in deepcopy
>     y = _reconstruct(x, rv, 1, memo)
>   File "C:\Anaconda3\lib\copy.py", line 297, in _reconstruct
>     state = deepcopy(state, memo)
>   File "C:\Anaconda3\lib\copy.py", line 155, in deepcopy
>     y = copier(x, memo)
>   File "C:\Anaconda3\lib\copy.py", line 243, in _deepcopy_dict
>     y[deepcopy(key, memo)] = deepcopy(value, memo)
>   File "C:\Anaconda3\lib\copy.py", line 166, in deepcopy
>     y = copier(memo)

I am trying to use:

column_descriptions = {'s3diff': 'output'}
ml_predictor = Predictor(type_of_estimator='regressor', column_descriptions=column_descriptions)
ml_predictor.train(X_train)

Using Windows 10 64bit, PTVS, python 3.5  Anaconda distro numpy version 1.12.0

Here is a small sample of the data in csv fromat:

s1,s2,s3,z1,z2,z3,s3diff
0.013559228178703498,0.025673357785545674,0.054246621518769716,0.0019039451760423324,0.0023811203598460453,0.008979818636014408,-0.00044262142281056843
0.013565574350913752,0.02567456687888959,0.05427293659974362,0.0018950401329676898,0.002375412193837593,0.008973971795195984,-0.0005004106844857525
0.013570379967844295,0.02567511670143283,0.05429903502472458,0.001885574961102246,0.002369474695989751,0.008968100260109748,-0.0005579600955363807
0.013508054303235838,0.025634770837291182,0.05430893657538927,0.001878011458290236,0.002364296215424333,0.008962307212474966,-0.0005992894613873756
0.013511602609961712,0.025634481169883244,0.05433465609179345,0.001868753716462282,0.002358432348394757,0.00895644722429477,-0.0006588159796903567
0.013513700507681331,0.02563355565235777,0.05436016223855941,0.001859419647459849,0.002352536562359934,0.008950592602950922,-0.0007156974742899835
0.013514391305573359,0.025632003766165676,0.054385456175574456,0.0018503606695955683,0.0023467437851787797,0.00894474510140853,-0.0007723436742973419
0.013513716868915206,0.025629834837153337,0.05441053905442364,0.0018413902979262547,0.0023409881948736736,0.008938919281015862,-0.0008287557548883745
0.013450119553814184,0.025587882382037484,0.054419595962235286,0.001854352953255216,0.002343926496141209,0.00893375061056522,-0.0008691188267534594
0.013386777814905954,0.025545849267344527,0.05442852055333747,0.0018508048645047013,0.002340393603631607,0.008928115639926697,-0.0009093265677538179
0.013323691348976123,0.02550373737629834,0.05443731348446538,0.0018416924640004707,0.0023346113381929354,0.00892230270352201,-0.0009493796581290725
0.013260859838861815,0.0254615485701288,0.05444597540841335,0.001835304304074932,0.002329948111117238,0.008916590220728613,-0.0009892787741490603
0.013198282953775365,0.025419284688339143,0.054454506974065724,0.0018288390671686878,0.002325261752092658,0.00891088097130443,-0.0010290245881449042
0.01313596034962186,0.025376947548969384,0.05446290882642744,0.0018223161630460574,0.002320559500834023,0.00890517549641675,-0.0010686177685395107
0.013073891669310734,0.025334538948855814,0.054471181606654345,0.0018132261856873175,0.002314754709712873,0.008899370877674928,-0.0011080589798779306
0.01301207654306164,0.025292060663886902,0.05447932595208324,0.001804296587586618,0.0023090425250402204,0.008893586829951936,-0.0011473488828574324
0.012950514588704706,0.02524951444925555,0.054487342496261394,0.0018060599788262445,0.0023073132657298033,0.008888017596813326,-0.001186488134357025
0.012889205411974951,0.025206902039707345,0.0544952318689762,0.0017980637482124453,0.002301992356231753,0.008882278618614799,-0.0012278338231271546
0.012828148606801568,0.025164225149785897,0.0545029946962841,0.0018081866368705492,0.002303532575535176,0.008876923566419309,-0.0012690234464503086
0.012767343755591552,0.02512148547407413,0.05451063160053942,0.0017991229857606476,0.0022977632192500924,0.008871148028440896,-0.0013077024835957893
0.012769012369507336,0.025116900259796127,0.05453364766297649,0.001813058039734092,0.002300903393992256,0.008865907504424043,-0.001361737950984966
0.012769360795593728,0.02511175543442325,0.05455646534993494,0.0018040366016910095,0.0022951689854805012,0.008860147479516639,-0.0014179000626484766
0.012708223794945827,0.025068308668128217,0.054563646810826434,0.001854930281172579,0.0023133418414137785,0.008856113699041393,-0.001458396584914777
0.012647349666553138,0.02502481013338672,0.054570705112575536,0.0018456335914751106,0.002307550562025229,0.008850359821925577,-0.0014963941258895749
0.012586737761005141,0.024981261384899724,0.05457764085771905,0.001836421055512864,0.002301779200491789,0.00884460816485268,-0.0015342465036939856
0.012526387421731532,0.02493766395929931,0.05458445464527198,0.0018272159564852665,0.002296014554570868,0.00883886432470322,-0.0015742934058071074
0.012466297985204895,0.02489401937535991,0.054591147070754416,0.0018187816574252059,0.002290587473257975,0.00883316094611504,-0.0016141897380302706
0.012406468781139459,0.02485032913420673,0.05459771872621798,0.0018105437265131766,0.00228524120194514,0.008827469027375913,-0.0016539361338125185
0.012346899132686176,0.02480659471952132,0.054604170200272084,0.001801895176806887,0.0022797185778127608,0.008821765538278467,-0.001693533223073078
0.012287588356624088,0.02476281759774416,0.05461050207810991,0.0017928632816352238,0.0022740109188885125,0.008816044195852147,-0.0017329816322275982
0.012228535763548121,0.024718999218274758,0.05461671494153414,0.0017839182914947218,0.002268343284774917,0.008810332962087566,-0.0017722819842141762
0.012190380524813702,0.02465822807576224,0.05460996197769378,0.0019530591920482493,0.0023357445281910224,0.008809790269395691,-0.0017985875072303317
0.012152027320046672,0.0245976007206724,0.054603144695083636,0.0019664756012967802,0.002340150370267237,0.008804882473128146,-0.0018247997507327487
0.012113484266560823,0.02453711685627856,0.05459626340172515,0.001959129136024505,0.00233555169661513,0.008799300862588592,-0.0018509190636184086
0.012074759291862277,0.02447677618611344,0.05458931840408654,0.0019567204470849696,0.002333181929725293,0.00879390128802838,-0.0018769457931449227
0.012035860138359307,0.024416578413972264,0.054582310007092336,0.0019470489834489363,0.0023273550909765164,0.008788205267805915,-0.0019028802849402823
0.011996794367930216,0.024356523243915875,0.05457523851413292,0.0019373358731604809,0.002321526918039432,0.008782516719558231,-0.0019287228830126985
0.011957569366356514,0.024296610380273663,0.05456810422707402,0.0019284450195471649,0.0023159414778455146,0.008776834599408973,-0.001954473929760288
0.011918192347624429,0.024236839527646638,0.05456090744626599,0.0019187787987123247,0.0023101536878058467,0.008771162173124231,-0.0019801337659806004
0.01187867035810077,0.02417721039091034,0.05455364847055322,0.0019118473851675265,0.0023052777511997674,0.008765521856344589,-0.0020057027308802503
0.011839010280586716,0.02411772267521776,0.054546327597283326,0.0019024739097574879,0.0022995430708183467,0.008759851856477594,-0.0020311811620843667
0.0117992188382551,0.02405837608600221,0.0545389451223163,0.0019478286296415687,0.0023158205017795074,0.00875554451505256,-0.0020542397042248306
0.011759302598474571,0.0239991703289802,0.05453150134003368,0.0019522279747085766,0.0023156544663118107,0.008750203451535377,-0.0020772149670288263
0.011719267976524398,0.023940105110154174,0.054523996543347504,0.0019456456015733415,0.0023113447072803553,0.008744687077025966,-0.0021001072652104963
0.011665441745914405,0.023898199505075355,0.054529057132776684,0.001991403833854338,0.0023285381890272064,0.008740479055462037,-0.0021355430210650357
0.011625842905863736,0.02383933858874879,0.05452140188835389,0.0020378207771872816,0.0023474338278313637,0.008736675334207097,-0.0021582410363757553
0.011586130156010021,0.023780617772820888,0.0545136865923974,0.002028293472634156,0.002341925995886439,0.008731080091650491,-0.002183168423070349
0.011546309626009728,0.02372203676142736,0.054505911531625435,0.002024640394274643,0.0023391102193999185,0.00872570870756183,-0.002208007662315263
0.011506387303752929,0.023663595259025963,0.054498076991333286,0.0020705932140323577,0.0023584836778079753,0.008721984691592308,-0.0022304488641252465
0.011504820296663262,0.02360474283407136,0.0544848006629512,0.002064819672853339,0.002354332521022209,0.008716440667074618,-0.0022474264863170945
0.011464188221225273,0.023546596862962482,0.05447686148324553,0.0020566020102002203,0.002349554492810748,0.00871093391482995,-0.00226971948720274
0.011423480130407972,0.02348858935117801,0.05446886362827441,0.0020467950646676594,0.0023439874858893137,0.00870536120024183,-0.0022919320643605
0.011382701311019143,0.023430720005828846,0.05446080737791378,0.002043408266960286,0.002340796877843424,0.008699886219496866,-0.0023163601218715857
0.01134185692765897,0.0233729885343492,0.054452693010658006,0.002033166266561129,0.002334945378918573,0.008694287553799626,-0.002338406819134019
0.01130095202551085,0.023315394644499002,0.054444520803628084,0.0020230756316765575,0.0023291123954945663,0.008688687191518248,-0.0023603740066865803
0.011259991533057907,0.023257938044366232,0.054436291032579916,0.0020204429079727373,0.0023262424044646515,0.008683245217363236,-0.002384549782759357
0.011218980264728309,0.02320061844236921,0.05442800397191258,0.002010497101308475,0.002320458155020935,0.008677654426110541,-0.0024086402101821183
0.01117792292347104,0.023143435547258832,0.05441965989467639,0.002004231074534517,0.002316112947665437,0.00867213627600161,-0.0024326456010103077
0.011136824103264628,0.02308638906812087,0.0544112590725809,0.0019949680295926683,0.002310576719871535,0.008666561923945137,-0.002456566265877584
0.01109568829156093,0.02302947871437809,0.05440280177600298,0.001985060691094221,0.00230480815674262,0.008660987087134692,-0.002480402514004117
0.011054519871665624,0.02297270419579251,0.05439428827399482,0.0019765417376367946,0.002299556680865311,0.00865543464790217,-0.0025041546532047487
0.011013323125058441,0.02291606522246749,0.054385718834291635,0.001970013650265254,0.0022953984308796103,0.008650018536732557,-0.002527822989897039
0.010972102233653344,0.02285956150484988,0.05437709372331969,0.0019614439280609707,0.0022903121731772487,0.00864453094351951,-0.002551407829109412
0.010930861282002349,0.02280319275373209,0.054368413206203926,0.0019516264326002086,0.0022845762860461386,0.008638979172358997,-0.002574909474489025
0.0108896042594434,0.022746958680254187,0.054359677546775766,0.0019418636474715996,0.0022788552618840754,0.008633432148897459,-0.002598328228309805
0.010848335062193992,0.02269085899590584,0.05435088700758075,0.0019321441212167376,0.002273148111783883,0.008627890630330086,-0.0026216643914802953
0.010807057495393476,0.02263489341252843,0.054342041849886114,0.0019224732267363015,0.002267455276143031,0.008622354228143841,-0.002644918263551427
0.010765775275094008,0.02257906164231696,0.05433314233368836,0.0019128507237700433,0.0022617767192683264,0.008616822934457443,-0.002668090142724344
0.010724492030202508,0.022523363397822026,0.05432418871772077,0.001903262467636266,0.002256116109872566,0.008611299141820985,-0.00269118032585812
0.010683211304375084,0.022467798391951756,0.0543151812594608,0.001893741850811182,0.002250466521611572,0.008605777668239945,-0.0027141891084773023
0.010641936557865059,0.02241236633797363,0.054306120215137484,0.001884263081207333,0.0022448305671146297,0.008600261669814575,-0.0027371167847796423
0.010600671169326285,0.02235706694951648,0.05429700583973879,0.0018748268603758398,0.0022392086203049575,0.008594751179955071,-0.0027599636476436096
0.010559418437572498,0.02230189994057221,0.05428783838701888,0.0018654378343998027,0.002233600766655965,0.008589245765984615,-0.002782729988635796
0.010518181583294376,0.02224686502549764,0.054278618109505336,0.0019087983842447863,0.0022508229746264034,0.008585411511030979,-0.0028054160980184803
0.010570763458137095,0.022197162880254626,0.05425955890603258,0.0018992683712523407,0.0022452313012324017,0.008579925360587036,-0.002818235912283154
0.010620487961520366,0.02214753866047561,0.05424048257720775,0.0018897512344228503,0.0022396109066875045,0.008574436285762281,-0.002831011269616664
0.010610768351900128,0.02209263983972696,0.05422597748170997,0.0018900770197416519,0.002237804071939397,0.008569143246581739,-0.002848330566200638
0.01056723731066494,0.02203818106329757,0.05421661060995624,0.0018818892244387253,0.002232859678600047,0.008563731056232794,-0.0028707608298776943
0.010523771352359731,0.021983852256858602,0.05420719196317855,0.0018835030322470767,0.002231601863692089,0.008558479967097094,-0.0028933403074783014
0.0104803726789851,0.0219296531431302,0.05419772178750642,0.0018753446399850848,0.002226658397005774,0.008553075574545299,-0.002915461931510592
0.01043704343690293,0.021875583445160263,0.05418820032788741,0.0018659531395867773,0.0022210821718473685,0.008547609590344512,-0.0029375055412217896
0.010393785717986392,0.021821642886326476,0.05417862782809407,0.0018572069613044355,0.0022158507068105932,0.008542187589241716,-0.0029594714164015296
0.010350601560744332,0.02176783119033822,0.05416900453073065,0.001847932316766983,0.0022103387415268023,0.008536739676137191,-0.0029813598355985862
0.01030749295142123,0.02171414808123859,0.05415933067723993,0.0018386886707716984,0.0022048036175278413,0.008531287960187496,-0.003003171076127839
0.010264461825073012,0.021660593283406283,0.05414960650790991,0.001830150877409216,0.0021996470576324577,0.008525884090973315,-0.003024905414077205
0.010310465021048472,0.021612565266183503,0.05413019820821178,0.001839956044051295,0.0022024874727104766,0.008521081824488363,-0.0030343558363755962
0.010353884977568095,0.02156460927909309,0.05411077440689032,0.0018307358212517179,0.0021969865145398198,0.008515650362975972,-0.003046340779716335
0.010394815863108527,0.02151672552692465,0.05409133520688726,0.0018215686579047645,0.0021914852118905107,0.008510219864373005,-0.0030582838385442845
0.0104333471701438,0.021468914210741517,0.05407188071067569,0.001815838880576729,0.002187627021412121,0.008504941217645742,-0.003070185150859897
0.010469564044330923,0.021421175527918758,0.05405241102026247,0.0018068122253075468,0.002182221298956184,0.008499533363662725,-0.00308204485412613
0.010503547583450288,0.021373509672180973,0.05403292623719054,0.00179785283733799,0.00217684292663273,0.00849413218091673,-0.0030938630852709176
0.010535375109487896,0.021325916833639488,0.05401342646254133,0.0017903552471015796,0.002172174780903196,0.008488800703703291,-0.0031030742555169387
0.01056512041679863,0.021278397198829284,0.05399391179693703,0.0017816062128506703,0.0021667779723192945,0.008483390233506917,-0.0031122513834338297
0.010592853998920557,0.021230950950745675,0.05397438234054292,0.001773046097260652,0.002161587937738016,0.00847801995141834,-0.003121394584894452
0.01061864325628046,0.02118357826888032,0.053954838193069635,0.0017665041693398407,0.00215733788488284,0.008472734359764365,-0.0031305039753074665
0.010642552686760098,0.021136279329257168,0.05393527945377556,0.0017579910542752837,0.0021520094866035065,0.00846733844880301,-0.003139579669619634
0.010664644060855504,0.021089054304467912,0.053915706221469004,0.0017505645764610113,0.002147346343272366,0.00846202689982342,-0.003148621782318034
0.0108473309915792,0.02107012566870884,0.053888961163485634,0.0018621749127376856,0.0021936119286705413,0.008460260314797949,-0.003150472996407347
0.011020635526236448,0.02105093669777698,0.05386222491472418,0.001853712916911929,0.0021886739011232528,0.008454946474122055,-0.003152313962445641
0.01118514614667312,0.021031491276802847,0.053835497495069336,0.0018599750971050274,0.0021905328785648,0.008450159004262795,-0.0031541447159671447

**Comment by azuric** [comment]
Guys you need to go back to numpy 1.11 to get it to work.

**Comment by ClimbsRocks** [comment]
That's a new error. what version of sklearn are you using? i know they had to release a couple of hotfixes when numpy released v1.12. 

Thanks for filing the issue, and following up with the fix! would love to hear any other info you gather (if the error shows up for all datasets, or just this one, what types of inputs throw it off, etc.)

also, looks like numpy saw and fixed this bug with v1.12.1: https://github.com/numpy/numpy/pull/8704

let me know if this is still an issue and i'll keep it open, otherwise i'll close in a day or two!

thanks again for filing this. let me know if you run into any other issues!

**Comment by azuric** [comment]
No problems I have run it on a couple of data sets now and the fix is
working. It's high frequency trading data btw.  I am trying to see if you
can beat my linear models based on ridge regression with manual features
based on online exponential smoothing.

So far tested on changes in volatility. Deep regression didn't perform well
but plain vanilla , out of sample it seems reasonably close to ridge. I
guess overfitting in deep is too easy where you have low signal to noise
ratio and regime changes.

What you are doing is very cool though will keep playing with it and test
more.

**Comment by ClimbsRocks** [comment]
keep me posted as you play with the package more! i love feedback, and new ideas, and stories of how people are using this. thanks again for both filing the issue, and sharing the fix!
