### ISSUE TITLE
Argument 'X' has incorrect type (expected numpy.ndarray, got csr_matrix)

### ISSUE THREAD

**Issue by vkocaman** [ClimbsRocks/auto_ml#335]
Hi all,

I just installed auto_ml and tried to use for the first time.. But even in Boston_dataset, I always get the following error in Jupiter notebook..

Can anyone help me with that?

Best regards,

It’s basically is like that:

Argument 'X' has incorrect type (expected numpy.ndarray, got csr_matrix)

and the details..

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-2b110959d739> in <module>()
     11 ml_predictor = Predictor(type_of_estimator='regressor', column_descriptions=column_descriptions)
     12 
---> 13 ml_predictor.train(df_train)
     14 
     15 ml_predictor.score(df_test, df_test.MEDV)

/Users/vkocaman/anaconda/envs/py36/lib/python3.6/site-packages/auto_ml/predictor.py in train(self, raw_training_data, user_input_func, optimize_final_model, write_gs_param_results_to_file, perform_feature_selection, verbose, X_test, y_test, ml_for_analytics, take_log_of_y, model_names, perform_feature_scaling, calibrate_final_model, _scorer, scoring, verify_features, training_params, grid_search_params, compare_all_models, cv, feature_learning, fl_data, optimize_feature_learning, train_uncertainty_model, uncertainty_data, uncertainty_delta, uncertainty_delta_units, calibrate_uncertainty, uncertainty_calibration_settings, uncertainty_calibration_data, uncertainty_delta_direction, advanced_analytics, analytics_config, prediction_intervals, predict_intervals, ensemble_config, trained_transformation_pipeline, transformed_X, transformed_y, return_transformation_pipeline, X_test_already_transformed)
    637 
    638         # This is our main logic for how we train the final model
--> 639         self.trained_final_model = self.train_ml_estimator(self.model_names, self._scorer, X_df, y)
    640 
    641         if self.ensemble_config is not None and len(self.ensemble_config) > 0:

/Users/vkocaman/anaconda/envs/py36/lib/python3.6/site-packages/auto_ml/predictor.py in train_ml_estimator(self, estimator_names, scoring, X_df, y, feature_learning, prediction_interval)
   1159         # Use Case 1: Super straightforward: just train a single, non-optimized model
   1160         elif (feature_learning == True and self.optimize_feature_learning != True) or (len(estimator_names) == 1 and self.optimize_final_model != True):
-> 1161             trained_final_model = self.fit_single_pipeline(X_df, y, estimator_names[0], feature_learning=feature_learning, prediction_interval=False)
   1162 
   1163         # Use Case 2: Compare a bunch of models, but don't optimize any of them

/Users/vkocaman/anaconda/envs/py36/lib/python3.6/site-packages/auto_ml/predictor.py in fit_single_pipeline(self, X_df, y, model_name, feature_learning, prediction_interval)
    835             print(start_time)
    836 
--> 837         ppl.fit(X_df, y)
    838 
    839         if self.verbose:

/Users/vkocaman/anaconda/envs/py36/lib/python3.6/site-packages/auto_ml/utils_model_training.py in fit(self, X, y)
    223 
    224                     self.model.set_params(n_estimators=num_iter, warm_start=warm_start)
--> 225                     self.model.fit(X_fit, y)
    226 
    227                     if self.training_prediction_intervals == True:

/Users/vkocaman/anaconda/envs/py36/lib/python3.6/site-packages/sklearn/ensemble/gradient_boosting.py in fit(self, X, y, sample_weight, monitor)
   1005                                     self.estimators_.shape[0]))
   1006             begin_at_stage = self.estimators_.shape[0]
-> 1007             y_pred = self._decision_function(X)
   1008             self._resize_state()
   1009 

/Users/vkocaman/anaconda/envs/py36/lib/python3.6/site-packages/sklearn/ensemble/gradient_boosting.py in _decision_function(self, X)
   1123         # not doing input validation.
   1124         score = self._init_decision_function(X)
-> 1125         predict_stages(self.estimators_, X, self.learning_rate, score)
   1126         return score
   1127

**Comment by ClimbsRocks** [comment]
That's weird. The tests still pass on my machine and on Travis, and I haven't touched that part of the codebase in a bit. 

Can you tell me which versions of the packages you're using (`pip freeze`)? My current guess is that there's some outdated package causing it. `auto_ml` latest is 2.7.6 as of this morning, and sklearn latest is `0.19.0`. In the meantime, try using other estimators! Try `pip install lightgbm`, and then feeding in `model.train(df_train, model_names='LGBMRegressor')`

**Comment by ClimbsRocks** [comment]
Sorry, meant to post that earlier. I just spent the morning playing around with the code to fix an unrelated issue (lightgbm had a breaking version update), and couldn't reproduce the bug you're reporting, which makes me think the version theory is probably correct here. 

Another possible solution if your local environment is weird, is to start a virtualenv (super simple if you haven't done it before), or to use docker (i've already got an image built here: https://hub.docker.com/r/climbsrocks/auto_ml_tests/).

**Comment by vkocaman** [comment]
Hi preston,

The version installed are stated below.. I tried several more times but still get same errors.. I use Anaconda with Python 3.6 on MacOS..

Thanks

alabaster==0.7.10
anaconda-client==1.6.3
anaconda-navigator==1.6.2
anaconda-project==0.6.0
appnope==0.1.0
appscript==1.0.1
asn1crypto==0.22.0
astroid==1.4.9
astropy==1.3.2
auto-ml==2.7.5
Babel==2.4.0
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.6.0
bitarray==0.8.1
blaze==0.10.1
bleach==1.5.0
bokeh==0.12.5
boto==2.46.1
Bottleneck==1.2.1
cffi==1.10.0
chardet==3.0.3
click==6.7
cloudpickle==0.2.2
clyent==1.2.2
colorama==0.3.9
ConfigSpace==0.3.10
contextlib2==0.5.5
cryptography==1.8.1
cycler==0.10.0
Cython==0.25.2
cytoolz==0.8.2
dask==0.14.3
datashape==0.5.4
deap==1.0.2
decorator==4.0.11
dill==0.2.7.1
distributed==1.16.3
docutils==0.13.1
entrypoints==0.2.2
et-xmlfile==1.0.1
fastcache==1.0.2
Flask==0.12.2
Flask-Cors==3.0.2
gevent==1.2.1
greenlet==0.4.12
h5py==2.7.0
HeapDict==1.0.0
html5lib==0.9999999
idna==2.5
imagesize==0.7.1
ipykernel==4.6.1
ipython==5.3.0
ipython-genutils==0.2.0
ipywidgets==6.0.0
isort==4.2.5
itsdangerous==0.24
jdcal==1.3
jedi==0.10.2
Jinja2==2.9.6
joblib==0.11
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.0.1
jupyter-console==5.1.0
jupyter-core==4.3.0
Keras==2.0.8
lazy-object-proxy==1.2.2
liac-arff==2.1.1
llvmlite==0.18.0
locket==0.2.0
lockfile==0.12.2
lxml==3.7.3
Markdown==2.6.9
MarkupSafe==0.23
matplotlib==2.0.2
mistune==0.7.4
mpmath==0.19
msgpack-python==0.4.8
multipledispatch==0.4.9
multiprocess==0.70.5
navigator-updater==0.1.0
nbconvert==5.1.1
nbformat==4.3.0
networkx==1.11
nltk==3.2.3
nose==1.3.7
notebook==5.0.0
numba==0.33.0
numexpr==2.6.2
numpy==1.12.1
numpydoc==0.6.0
odo==0.5.0
olefile==0.44
openpyxl==2.4.7
packaging==16.8
pandas==0.20.3
pandocfilters==1.4.1
partd==0.3.8
pathlib2==2.2.1
pathos==0.2.1
patsy==0.4.1
pep8==1.7.0
pexpect==4.2.1
pickleshare==0.7.4
Pillow==4.1.1
ply==3.10
pox==0.2.3
ppft==1.6.4.7.1
prompt-toolkit==1.0.14
protobuf==3.4.0
psutil==5.2.2
ptyprocess==0.5.1
py==1.4.33
pycosat==0.6.2
pycparser==2.17
pycrypto==2.6.1
pycurl==7.43.0
pyflakes==1.5.0
Pygments==2.2.0
pylint==1.6.4
pynisher==0.4.2
pyodbc==4.0.16
pyOpenSSL==17.0.0
pyparsing==2.1.4
pytest==3.0.7
python-dateutil==2.6.0
pytz==2017.2
PyWavelets==0.5.2
PyYAML==3.12
pyzmq==16.0.2
QtAwesome==0.4.4
qtconsole==4.3.0
QtPy==1.2.1
requests==2.14.2
rope-py3k==0.9.4.post1
scikit-image==0.13.0
scikit-learn==0.18.1
scikit-MDR==0.4.4
scipy==0.19.0
seaborn==0.7.1
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
sklearn-deap2==0.2.1
skrebate==0.3.4
snowballstemmer==1.2.1
sortedcollections==0.5.3
sortedcontainers==1.5.7
Sphinx==1.5.6
sphinx-rtd-theme==0.2.4
spyder==3.1.4
SQLAlchemy==1.1.9
statsmodels==0.8.0
stopit==1.1.1
sympy==1.0
tables==3.3.0
tabulate==0.8.1
tblib==1.3.2
tensorflow==1.3.0
tensorflow-tensorboard==0.1.8
terminado==0.6
testpath==0.3
toolz==0.8.2
tornado==4.5.1
TPOT==0.9.0
tqdm==4.19.1.post1
traitlets==4.3.2
typing==3.6.2
unicodecsv==0.14.1
update-checker==0.16
wcwidth==0.1.7
Werkzeug==0.12.2
widgetsnbextension==2.0.0
wrapt==1.10.10
xlrd==1.0.0
XlsxWriter==0.9.6
xlwings==0.10.4
xlwt==1.2.0
zict==0.1.2

**Comment by ClimbsRocks** [comment]
try upgrading scikit-learn

**Comment by vkocaman** [comment]
Now it works.. thanks:-)

**Comment by ClimbsRocks** [comment]
heck yeah! weird that that broke between versions. i'll try to see if i can update to be compatible with both. 

thanks for filing the issue! would love to know anything else you run into
