### ISSUE TITLE
LSTM

### ISSUE THREAD

**Issue by pasha76** [ClimbsRocks/auto_ml#345]
I am new to the concept. Can anyone tell me if auto_ml supports keras LSTM, RNN etc? Is there any deeplearning sample by the way?

**Comment by ClimbsRocks** [comment]
using a standard feed forward neural net is easy! 

`ml_predictor.train(data, model_names=['DeepLearningRegressor'])`

however, we don't support anything other than feed forward neural nets at the moment. each other type of neural net tends to rely on different data processing. you do very different formating to go from raw data to nn input for images than you do for sound than you do for time series. 

we're hoping to build out this functionality in http://autodeep.net, but that project is still in it's infancy. if you want to jump in and help on that one, we'd love it!
