### ISSUE TITLE
boston prices example

### ISSUE THREAD

**Issue by oshefter** [ClimbsRocks/auto_ml#354]
Hello, 

I was trying to run your sample code with Boston prices and getting the error.
I was just following your README file. Do you know why I am getting this error?

Thanks and regards, 
-Olga Shefter

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\gradient_boosting.py in fit(self, X, y, sample_weight, monitor)
   1005                                     self.estimators_.shape[0]))
   1006             begin_at_stage = self.estimators_.shape[0]
-> 1007             y_pred = self._decision_function(X)
   1008             self._resize_state()
   1009 

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\gradient_boosting.py in _decision_function(self, X)
   1123         # not doing input validation.
   1124         score = self._init_decision_function(X)
-> 1125         predict_stages(self.estimators_, X, self.learning_rate, score)
   1126         return score
   1127 

TypeError: Argument 'X' has incorrect type (expected numpy.ndarray, got csr_matrix)

**Comment by ClimbsRocks** [comment]
Try upgrading auto_ml to the latest version with `pip install --upgrade auto_ml`. The error's very likely caused by version mismatches between auto_ml and scikit-learn, when scikit-learn made some breaking changes to their API. upgrading to the latest auto_ml should fix it, but let me know if you encounter any other issues.

**Comment by oshefter** [comment]
Thank you. It worked indeed!

Regards,

-Olga

**Comment by sharpe5** [comment]
@oshefter If you could close this issue off, that would be great thanks!

**Comment by oshefter** [comment]
Thank you. Closing the issue.
