### ISSUE TITLE
lgbm max_bin parameter will be deprecated

### ISSUE THREAD

**Issue by alvinthai** [ClimbsRocks/auto_ml#365]
I haven't actually used lgbm in ```auto_ml``` myself yet and only see this error in my own prototype code, but this seems like an optimization issue that will creep up in ```auto_ml```.

It looks like ```max_bin``` parameter in lgbm is deprecated and has no affect on the grid search for lgbm models. If you try passing in max_bin as a parameter to an LGBMClassifier object and run a fit, you get this message:
```
/home/ubuntu/anaconda2/lib/python2.7/site-packages/lightgbm/basic.py:642: UserWarning: max_bin keyword has been found in `params` and will be ignored. Please use max_bin argument of the Dataset constructor to pass this parameter.
  'Please use {0} argument of the Dataset constructor to pass this parameter.'.format(key))
/home/ubuntu/anaconda2/lib/python2.7/site-packages/lightgbm/basic.py:648: LGBMDeprecationWarning: The `max_bin` parameter is deprecated and will be removed in 2.0.12 version. Please use `params` to pass this parameter.
  'Please use `params` to pass this parameter.', LGBMDeprecationWarning)
```

I think this parameter can only be set in lightgbm.Dataset: http://lightgbm.readthedocs.io/en/latest/Python-API.html

Which isn't really accessible from the LGBMClassifier and LGBMRegressor sklearn wrappers, I think they construct the Dataset objects from the X and y input.

**Comment by ClimbsRocks** [comment]
thanks for the thorough report! that was way more useful than the warning the library was throwing. 

the warning was being thrown in two locations: 1. grid search (as you referenced), but also 2. by the sklearn api itself (ie, lgbm threw that warning sometime between creating an instance of LGBMRegressor and their underlying C library). 

i just solved the grid search part, and i think i remember that a recent lgbm release solved the second part. 

if you haven't used lgbm yet, it's definitely my favorite ml library of the moment! super fast, easily parallelized across all cores on the machine, and handles categorical features natively (no need to one-hot-encode). catboost claims to be pretty similar. 

closing this under the assumption that i get a new release out tonight with the updates :)

**Comment by alvinthai** [comment]
Oh cool, did not know LGBM had one-hot-encoding support built-in, I thought only catboost supported categorical features natively.

I do like the speed of LGBM, much faster than XGB. Though it seems most of the speed gains come from histogram-binning the feature space (hence the max_bin parameter). I believe XGB has histogram binning support as well (see https://medium.com/data-design/xgboosts-new-fast-histogram-tree-method-hist-a3c08f36234c), though I’m not sure if this is built into their sklearn wrapper and how speeds compare when utilizing this feature.
