### ISSUE TITLE
Question: Training fails with AttributeError  'DataFrame' object has no attribute 'FR_Incrementing'

### ISSUE THREAD

**Issue by Rainer-Kempkes** [ClimbsRocks/auto_ml#371]
hi,
I am running into an error when training: 
`ml_predictor.train(df, model_names=['LogisticRegression', 'GradientBoostingClassifier', 'RandomForestClassifier', 'ExtraTreesClassifier', 'AdaBoostClassifier'])`
After he has finished to train the single models he fails at "Calculating feature responses, for advanced analytics." with the error: 
`AttributeError: 'DataFrame' object has no attribute 'FR_Incrementing'`

I am using Python 3.6 and have already re-installed pandas, numpy and auto_ml. Any help welcome,
Rainer

complete Traceback:

> Traceback (most recent call last):
> File "C:/Users/xyzr/AppData/Local/Temp/scp39208/data/images/df_pybandit/sim_automl.py", line 40, in <module> analyze()
>   File "C:/Users/xyzr/AppData/Local/Temp/scp39208/data/images/df_pybandit/sim_automl.py", line 21, in analyze
>     ml_predictor.train(df, model_names=['LogisticRegression', 'GradientBoostingClassifier', 'RandomForestClassifier', 'ExtraTreesClassifier', 'AdaBoostClassifier'])
>   File "D:\Anaconda3\lib\site-packages\auto_ml\predictor.py", line 641, in train
>     self.trained_final_model = self.train_ml_estimator(self.model_names, self._scorer, X_df, y)
>   File "D:\Anaconda3\lib\site-packages\auto_ml\predictor.py", line 1217, in train_ml_estimator
>     gscv_results = self.fit_grid_search(X_df, y, grid_search_params, refit=True)
>   File "D:\Anaconda3\lib\site-packages\auto_ml\predictor.py", line 1170, in fit_grid_search
>     self.print_results(model_name, trained_final_model, X_df, y)
>   File "D:\Anaconda3\lib\site-packages\auto_ml\predictor.py", line 1038, in print_results
>     feature_responses['FR_Incrementing_abs'] = np.absolute(feature_responses.FR_Incrementing)
>   File "D:\Anaconda3\lib\site-packages\pandas\core\generic.py", line 3614, in __getattr__
>     return object.__getattribute__(self, name)
> AttributeError: 'DataFrame' object has no attribute 'FR_Incrementing'

**Comment by dsal1951** [comment]
I'm having the same issue.  I tried setting ml_for_analytics=False as well as skip_feature_responses=True, but neither had an effect

**Comment by ClimbsRocks** [comment]
bah, yeah, sorry about this, and my absence from the project for a bit. it's a bug i haven't seen myself or in my test suite, so it's totally caught me by surprise. 

i should be releasing a new version of auto_ml tonight that works around this. 

any chance you have some example code you could share with me that reproduces this bug? any chance you have an nlp column? would love to get to the heart of this, not just my workaround. 

thanks,
preston

**Comment by ClimbsRocks** [comment]
fixed in last night's v2.9.9 release available on pypi (`pip install --upgrade auto_ml`)
