### ISSUE TITLE
Calibrate_final_model doesnt accept y_test dataset

### ISSUE THREAD

**Issue by ardabeyazoglu** [ClimbsRocks/auto_ml#373]
Hi,

I'm ussing Xgboost classifier for my ml models. Without calibration everything works however when i use calibration, I got an error as following:
       
      Traceback (most recent call last):
      File "./automl_class_return.py", line 74, in <module>
       y_test=df_calibrate.Signal
      File "/home/ardabeyaz/.local/lib/python3.5/site-packages/auto_ml/predictor.py", line 651, in train
       self.trained_final_model.model = self._calibrate_final_model(self.trained_final_model.model, X_test, 
      y_test)
       File "/home/ardabeyaz/.local/lib/python3.5/site-packages/auto_ml/predictor.py", line 818, in 
     _calibrate_final_model
        calibrated_classifier = calibrated_classifier.fit(X_test_processed, y_test)
      File "/home/ardabeyaz/.local/lib/python3.5/site-packages/sklearn/calibration.py", line 157, in fit
      calibrated_classifier.fit(X, y)
       File "/home/ardabeyaz/.local/lib/python3.5/site-packages/sklearn/calibration.py", line 335, in fit
       df, idx_pos_class = self._preproc(X)
      File "/home/ardabeyaz/.local/lib/python3.5/site-packages/sklearn/calibration.py", line 294, in _preproc
       df = self.base_estimator.predict_proba(X)
      File "/opt/xgboost/python-package/xgboost/sklearn.py", line 539, in predict_proba
      ntree_limit=ntree_limit)
      File "/opt/xgboost/python-package/xgboost/core.py", line 1044, in predict
      self._validate_features(data)
      File "/opt/xgboost/python-package/xgboost/core.py", line 1288, in _validate_features
      data.feature_names))
      ValueError: feature_names mismatch: ['f0', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13'] 
      ['f0', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12']

Here is the code produces this error:

     # X is my dataset, containts typical OHLC data, some indicators and a Signal column (-1 or +1)
     train_split = int(0.8 * len(X))
     calibrate_split = int(0.9 * len(X))

     df_train = X[:train_split]
     df_calibrate = X[train_split:calibrate_split]

     y_predict = Predictor(type_of_estimator='classifier', column_descriptions={'Signal': 'output'})
     y_trained_model = y_predict.train(
         df_train,
         model_names=['XGBClassifier'],
         cv=5,
         calibrate_final_model=True,
         X_test=df_calibrate,
         y_test=df_calibrate.Signal
    )

**Comment by calz1** [comment]
I got errors like this once due to an outdated version of XGBoost from pip. What version do you have?

**Comment by ClimbsRocks** [comment]
oh ugh, yeah, xgboost was really, really messy with how it handled sparse datasets for a while. 

as calz1 said, i think they've fixed this recently. i don't know if the new xgboost on python (v0.7.post3) works or not, but i know their master release worked for a while when you installed directly from github. 

i also worked around this error in other parts of my codebase in recent versions of auto_ml, so it might be worth upgrading auto_ml too. 

if that doesn't work, let me know, and i can look into including the workaround hack for calibrating xgboost. but obviously, i'd prefer to avoid that if any of the version updates work :)

**Comment by ardabeyazoglu** [comment]
Hi again,

I cant reproduce it anymore, maybe it's fixed when upgraded the library recently. I'll let u know if i encounter it again. Thanks
