### ISSUE TITLE
can auto_ml Regressor support multi label

### ISSUE THREAD

**Issue by berisfu** [ClimbsRocks/auto_ml#378]
Can it support multi label？for example，if Label is location(Longitude,Latitude),can I use auto_ml REGRESSOR to predict a location which is multi-label.

**Comment by ClimbsRocks** [comment]
whoa, interesting question. 

you can certainly use auto_ml to predict multilabel classification problems, but unless your locations are a discrete number of buckets in the hundreds or less, that probably wouldn't work for you. 

we don't support multilabel regression problems (and i don't actually know offhand of any library that does). 

you might want to consider reframing your problem. you could do things like "distance_traveled" or "direction traveled" or "speed" or "arrived_on_time" or something else like that. but the problem as it's framed now probably won't work. 

feel free to repoen if you want to chat more! i love talking about how to structure ml problems- that's become one of my favorite parts of the process now that auto_ml takes care of a lot of the more boring parts :)
