### ISSUE TITLE
far future: take in dataframes or other sparse data structures directly

### ISSUE THREAD

**Issue by ClimbsRocks** [ClimbsRocks/auto_ml#41]
right now taking in python dictionaries is awesome for it's flexibility and ease of development, but is killing us on memory, even if it is a super sparse data structure. 

one workaround we could do for this is described in https://github.com/ClimbsRocks/auto_ml/issues/40, though that feels fairly hacky. taking in a DataFrame seems much more obvious.

**Comment by vishnumani2009** [comment]
@ClimbsRocks 
currently i am adding the dataframe support.
Just wanted to know you want to keep dictionary objects along with data frames?

**Comment by ClimbsRocks** [comment]
Hey @vishnumani2009 ! Sorry again for the delayed response time. 

I think it's totally fine to switch our internals to rely on only DataFrames. 

I'd still like to keep our API flexible to accept either. So what I'm picturing is that as soon as the user passes in a dataset, we immediately test whether it's a list of dictionaries, or a DataFrame. If it's a list of dictionaries, the first thing we do is convert it to a DataFrame. Then the rest of the internal workflow that's based on DataFrames should be good to go. 

Thanks again for working on this! Let me know if there's anything I can do to help. I just fixed that other bug you reported, but let me know if you run into anything else. 

Warmly,
preston

**Comment by vishnumani2009** [comment]
@ClimbsRocks 
I am currently end of completing data frame support.
This took my time as had to make changes through out  the code base.
Currently I have followed  approach specified by you above.

I am stuck at one point and need your help with following.
1.  I would like to know what does fit and transform method doing in CustomSparseScaler
2. I would like to what is returned from get_all_attribute_names() function
3.  I would like to know what does fit and transform method doing in  AddPredictedFeature
4.  I would like to know what does fit and transform method doing in  AddSubpredictorPredictions

best,
Mani

**Comment by ClimbsRocks** [comment]
Awesome! I'm becoming more and more excited by how easy (and memory efficient) DataFrames are. 

1. CustomSparseScaler is inspired by scikit-learn's [RobustScaler](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.RobustScaler.html). The goal is to find the 5th percentile value and the 95th percentile value for that column. We set these as 0 and 1, and then scale all values to fit between them. I wrote my own version to be compatible with sparse data, since scikit-learn's doesn't take sparse data by default. 
2. This function just figures out the list of columns (attribute names in current implementation) in our dataset. It ignores everything in column_descriptions (which is either categorical data which can't be scaled, output column, a column marked ignore, or the y values to train a subpredictor on). 
3. AddPredictedFeature can be deprecated for now. In it's current form it is used to run clustering on our input rows, and add the prediction for which cluster this row falls into as a feature. It's not super useful, and the code isn't great. 
4. One of the most powerful things auto_ml does is automatically train and ensemble subpredictors for you on sub-portions of your problem. Once we've trained up all our subpredictors, we want to run each row through the subpredictors to get predictions from them. AddSubpredictorPredictions is where we pass each row into each subpredictor to get it's prediction. 

Thanks so much for working on this PR. I'm excited to see the results! It should make working with large datasets much easier, and allow the user to do things like save their data in more efficient file formats like HDF5. Big Data here we come!

**Comment by vishnumani2009** [comment]
@ClimbsRocks 
Thank you the details.
Will send you the PR soon.

**Comment by vishnumani2009** [comment]
@ClimbsRocks 
Thanks for all the help.
I completed dataframe [support.](https://github.com/vishnumani2009/auto_ml/tree/Data-frame)
Currently i am testing it with multiple datasets.
I do have some questions with respect to certain part of the codes.
I will consolidate all of them and send you soon
Later in weekend i will send PR.

**Comment by ClimbsRocks** [comment]
heck yeah! awesome progress on this. feel free to ask any questions you have about any specific parts of the code. 

i think i'd actually prefer to submit a PR now, if you can. the new PR tools are really nice for having specific conversations about specific lines of code, and keeping it all nicely organized. 

either way, i'm super excited to support dataframes! i just crashed a few computers trying to load lists of dictionaries into memory that were too large :)

**Comment by vishnumani2009** [comment]
@ClimbsRocks 
PR sent succesfully waiting for you review.

Following are some of my additional questions.
Since this being an auto ML tool, we will be bench marking this sometime in future.
Lets say we have all of the fundamental functionality ready by June 2017 , why not take this to [auto ml challenge ](https://competitions.codalab.org/competitions/2321) and do a benchmark? what do you think?
See [here](http://www.causality.inf.ethz.ch/AutoML/automl_ijcnn15.pdf) for complete details on challenge.

Also i was planning if we could write a paper on auto_ml ,just to get a word out among user community.
Wanted to know your opinion on this?

**Comment by ClimbsRocks** [comment]
Thanks for the help here @vishnumani2009 ! For what it's worth, we're training on datasets at work that would easily overwhelm 128GB of RAM if our dataset were a list of dictionaries. Happily, with DataFrames, this is entirely doable.
