### ISSUE TITLE
support NLP

### ISSUE THREAD

**Issue by ClimbsRocks** [ClimbsRocks/auto_ml#9]

**Comment by vishnumani2009** [comment]
@ClimbsRocks  I would like to have a shot at this.What exact support in NLP are we looking here?

**Comment by ClimbsRocks** [comment]
@vishnumani2009 that's awesome! happy to have other contributors around. 

here's the type of use case i was thinking of supporting: 
classifying incoming messages to a company's support email by the type of request
classifying social media posts the company is tagged in by the type of message it is (sharing a bad experience, asking for a refund, asking a question, sharing how much they love the product, new feature request, feedback on a new feature launched, etc.). 

Obviously, this would be supervised learning assuming the company has a labeled dataset. 

For v1, I was picturing letting the user pass in a single text field with each row. This field would have to be labeled either "text" or "nlp" in the column_descriptions dictionary. Then, we'd go through and perform all the standard nlp transforms on the text "column" in each row (more on that below), and just feed in that data along with all the other features from that row to the rest of our pipeline as features. 

I think the rest of the pipeline should be able to handle NLP data, it's really just a matter of doing that initial feature transformation from the raw text in each field to features the algorithms can understand. 

For that feature transformation, I was thinking of using scikit-learn's [TfidfVectorizer](http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html). That keeps it all using that familiar scikit-learn API, and I've found it to be successful on previous projects. 

In terms of where this fits into the pipeline, here are the quick steps I can think of:

- [ ] Add in text or nlp as an acceptable field in column_descriptions
- [ ] Add in some logic to BasicDataCleaning.fit to fit the TfidfVectorizer to the data (gather all the documents, and feed them to TfidfVectorizer.fit() ), if we have an NLP/text column
- [ ] Add in some logic to BasicDataCleaning.transform for nlp/text columns. 

I'm not wildly in love with the approach of adding this logic into BasicDataCleaning, since it might use up more memory. If you'd prefer a different approach, I'm very open to hearing about it!

Post-v1 we can think about things like making the params for TfidfTransformer grid searchable, and allowing the user to pass in multiple text fields. But for now, we'll focus on the simple case. 

Thanks for taking this on! I'll be working on the project again shortly, so let's just cut separate branches for our work. Let me know if you have any questions/thoughts about this!

**Comment by vishnumani2009** [comment]
@ClimbsRocks 
Tfifdfvectorizer sounds good. 
I will create a separate branch called NLP and send a pull request as soon as its done.
As you said there will be a memory issue , especially with increasing data. But at the same time data size is  typical problem in any NLP task, hence memory consumption is unavoidable. 
 
At same time any thoughts on adding fast text (https://github.com/facebookresearch/fastText) ? this would serve the above & similar related use cases(fast,decently accurate,memory efficient). 
But considering long run &  automl's core idea of automating  tasks, adding feature transformers like tfidf etc.. would be helpful. 

Let me know your thoughts meanwhile i will get back to you if i have any further queries.

**Comment by ClimbsRocks** [comment]
@vishnumani2009 ooh, I hadn't run across Facebook's fastText before. Looks like a cool project!

You're totally right though for auto_ml- I think we just want to stick with scikit-learn's tfidfvectorizer as part of the already existing pipeline to keep it as simple and consistent as possible. 
Thanks for the link!

**Comment by vishnumani2009** [comment]
@ClimbsRocks 
I have completed the addition of tfidf vectorizer and tested the same with three datasets namely iris( for integrity of rest of the code), sentence classification (to check working of tfidf vectorizer), a datasets that has both sentences and other numerical features ( To make sure it work with mixed features).

I have committed to my branch https://github.com/vishnumani2009/auto_ml/commit/f56ec3005f6de8488b3e3a4ded7d57676ce644fe

Shall I send a pull request for review?
 or 
will you review directly?

**Comment by vishnumani2009** [comment]
Also I feel we can do some minor implementation changes as project progresses.
For example can we design all feature extractors  as transformer classes. 

Also do you have any plans of introducing data frames instead of dictionary objects? if we introduce i feel we can remove redundant loops and test conditions, hence make code more lesser,easier to understand & consistent.

**Comment by ClimbsRocks** [comment]
That's awesome! Submit a PR, and I'll look through it (probably some time this weekend). 

I would like to support DataFrames at some point. The idea behind dictionaries was that they'd be easier for people to get started with, but DataFrames would be much more efficient. If you want to take a crack at supporting DataFrames instead of dictionaries, I'm fully on board with that. We could let the user pass in either a list of dictionaries or a DataFrame, and just do the conversion ourselves inside of auto_ml. 

Thanks for the great work so far!

**Comment by vishnumani2009** [comment]
@ClimbsRocks 
I have submitted the PR, let me know if there can be any improvements done in the PR.
Meanwhile i will take a shot on Data frame support. I will be using pandas library for  data frames.
Will get back to you soon with next PR on data frames support.

**Comment by ClimbsRocks** [comment]
thanks for baking in nlp support!
