### ISSUE TITLE
Ridge classifier fails when tested on iris dataset.

### ISSUE THREAD

**Issue by vishnumani2009** [ClimbsRocks/auto_ml#93]
@ClimbsRocks 
I just synced your latest commits/changes ,since my last fork and tested the updated repo on iris data.
Ridge classifier fails to run & throws following error.

_line 678, in _print_ml_analytics_results_regression
    potential_impact = feature_ranges[col_idx] * trained_coefficients[col_idx]
IndexError: list index out of range_

I could see that feature_ranges list was of size 0.

Other classifiers work fine. except ridge.I am I training wrongly ? 
No changes in test script except i am using new iris.csv file(attached).
[IRIS.xlsx](https://github.com/ClimbsRocks/auto_ml/files/496321/IRIS.xlsx)

**Comment by ClimbsRocks** [comment]
Thanks for reporting this! Sorry it's taken me a little while to respond. I just fixed that in the release I just pushed out, v1.2.0. 

Let me know if you run into any other issues or if there's anything else I can do to help- I'll probably be more responsive over the upcoming weekend.
