### ISSUE TITLE
interpretation of predictor score

### ISSUE THREAD

**Issue by colingoldberg** [ClimbsRocks/auto_ml#97]
Hi Preston,

As a newbie to ml, with a lot to learn, I am trying to understand some basics by running auto_ml. So this is not a bug report, as much as a request for you to add more explanation and documentation for newbies (and others) like me. My current puzzle is how to interpret predictor score for the numerai dataset.

I got the following output from .train:

> > > ml_predictor.train(training_data, X_test=X_test, y_test=y_test, ml_for_analytics=True, print_training_summary_to_viewer=True)
> > > Welcome to auto_ml! We're about to go through and make sense of your data using machine learning
> > > Successfully performed basic preparations and y-value cleaning
> > > Created estimator_names and scoring

---

About to fit the pipeline for the model RidgeClassifier to predict target
Started at:
2016-09-30 18:11:57
Finished training the pipeline!
Total training time:
0:00:12

Here are the results from our RidgeClassifier
The following is a list of feature names and their coefficients. By default, features are scaled to the range [0,1] in a way that is robust to outliers, so the coefficients are usually directly comparable to each other.
This printed list will contain at most the top 50 features.
feature4: 0.0115
feature20: 0.0122
feature10: -0.0154
feature8: -0.0163
feature15: -0.0177
feature7: 0.0316
feature1: 0.0333
feature16: 0.0485
feature12: 0.0537
feature3: -0.0544
feature9: 0.0906
feature14: 0.0971
The results from the X_test and y_test data passed into ml_for_analytics (which were not used for training- true holdout data) are:
This model has no predict_proba method. Returning results of .predict instead.
-0.478738775931

---

About to fit the pipeline for the model XGBClassifier to predict target
Started at:
2016-09-30 18:12:11
Finished training the pipeline!
Total training time:
0:00:16

Here are the results from our XGBClassifier
Here are the feature_importances from the tree-based model:
The printed list will only contain at most the top 50 features.
feature18: 0.0808
feature7: 0.0837
feature20: 0.0851
feature10: 0.0924
feature14: 0.0952
feature15: 0.0952
feature21: 0.1053
feature1: 0.1111
feature4: 0.1111
feature5: 0.14
The results from the X_test and y_test data passed into ml_for_analytics (which were not used for training- true holdout data) are:
-0.249475642112

So I see that XGBClassifier produces -0.249475642112 and RidgeClassifier produces -0.478738775931. (XGBClassifier is therefore the selected estimator.) How do I interpret these values? - in the light of the type of data I am testing?

Just to give some context: I don't plan to be an ml geek. What I would like to do is integrate this capability into my (new) rule engine product so as to enable real-time (or near real-time) prediction. My focus is therefore more on the post-training stuff - where I would want to provide reliable predictive capability based on datasets that have been shown to have high training accuracy (and anything else I am yet to discover that would be important).

Thanks.

Colin Goldberg

**Comment by vishnumani2009** [comment]
@colingoldberg 
Thanks for using auto ml and thanks for pointing out issue on documentation.
Currently the scores that are returned brier score values for the test data rows
Description of which can be found [here](https://en.wikipedia.org/wiki/Brier_score)

If you want to use predicted class labels instead of score, you can change
print(ml_predictor.score(X_test, y_test)) 
to 
print(ml_predictor.predict(X_test))
which will return class labels for each row in the data set.
Details of the API are [here](http://auto-ml.readthedocs.io/en/latest/api_docs_for_geeks.html)

@ClimbsRocks 
I have opened an [#98](https://github.com/ClimbsRocks/auto_ml/issues/98) for adding details on scoring metrics as part of description

**Comment by colingoldberg** [comment]
What I would really like in this case, is to be able to see a "score" that I can compare with the results I see on the numer.ai site - I believe it is "logloss". Is this a reasonable quest?

Even as I don't understand logloss, it would be most useful - to give me some context - to relate any results I obtain with the following that I see (today) on their homepage.

ie.
1 Annual Rate=$39,600.00 PLACNET Career Earnings=$226.38 Logloss=0.64649
etc.

![image](https://cloud.githubusercontent.com/assets/2991417/19128383/1de86542-8b11-11e6-968d-f9dc1dd0a201.png)

Colin Goldberg

**Comment by ClimbsRocks** [comment]
@colingoldberg : hopefully the more verbose scoring that's been implemented over the past few months helps to answer this. I'll keep this issue open until I add in the actual logloss score to the verbose scoring.
