### ISSUE TITLE
Documentation: Addition of scoring metric details in description of ml_predictor.score

### ISSUE THREAD

**Issue by vishnumani2009** [ClimbsRocks/auto_ml#98]
@ClimbsRocks 
Based on issue [#97](https://github.com/ClimbsRocks/auto_ml/issues/97) I feel  we should add some details on scoring methods as part of the description of score method.This would help the newbies using auto ml. You have anything in mind for this?

**Comment by ClimbsRocks** [comment]
Great idea! I know when I first started, the scoring methods were somewhat opaque to me. I was a little worried about doing this before adding in support for more scoring metrics, but I think it's worthwhile, and might spark others to contribute other popular scoring metrics.

**Comment by ClimbsRocks** [comment]
finished!
